In [37]:
# Import libraries
import pandas as pd 
import numpy as np 
import math 
import statistics 
import matplotlib.pyplot as plt

**Clean First Dataset**:

In [77]:
# Import Subset data and create dataframe
raw_df = pd.read_csv(r".\Signal_data\Subset_2025-2026.csv", sep=";", engine="python") 

# Drop non-ES columns
raw_df_1 = raw_df[["Date (UTC)", "ES_DIR", "ES_Open"]].copy()

# Rename for convention
raw_df_1.columns = ["Date", "Signal", "Entry_Price"]

# Set Index
raw_df_1["Date"] = pd.to_datetime(raw_df_1["Date"])
raw_df_1 = raw_df_1.set_index("Date")
raw_df_1 = raw_df_1[raw_df_1.index.notna()]

# Change variable types
raw_df_1["Signal"] = raw_df_1["Signal"].fillna(0).astype("int64")
raw_df_1["Entry_Price"] = (raw_df_1["Entry_Price"].astype(str).str.replace(",", ".", regex=False))
raw_df_1["Entry_Price"] = pd.to_numeric(raw_df_1["Entry_Price"], errors="coerce")

# Preview
raw_df_1.tail()

            Signal  Entry_Price
Date
2026-03-15       1      6608.50
2026-03-16       1      6700.00
2026-03-17       1      6722.50
2026-03-18       1      6622.00
2026-03-19       0      6622.75

**Clean Second Dataset**:

In [91]:
# Import Q2_2026 data
raw_df = pd.read_csv(r".\Signal_data\Q2_2026-06-02.csv", engine="python") 

# Drop non-ES columns
raw_df_2 = raw_df[["utc_date", "ES_classification", "ES_refOpen"]].copy()

# Rename for convention
raw_df_2.columns = ["Date", "Signal", "Entry_Price"]

# Handle index
raw_df_2["Date"] = pd.to_datetime(raw_df_2["Date"], errors="coerce", dayfirst=True)
raw_df_2 = raw_df_2.dropna(subset=["Date"])
raw_df_2 = raw_df_2.set_index("Date") 
raw_df_2 = raw_df_2.sort_index() 

# Change string signal to polar signal 
mapping = {np.nan:0, "BULLISH":1, "BEARISH":-1} 
raw_df_2["Clean_Signal"] = raw_df_2["Signal"].map(mapping)
raw_df_2["Clean_Signal"] = raw_df_2["Clean_Signal"].ffill().fillna(0).astype(int) 
raw_df_2.drop(columns=["Signal"], inplace = True)
raw_df_2.rename(columns={"Clean_Signal":"Signal"}, inplace=True)
raw_df_2 = raw_df_2[["Signal", "Entry_Price"]]

# Preview
raw_df_2.head()

            Signal  Entry_Price
Date
2026-03-29       0      6380.00
2026-03-30       1      6385.25
2026-03-31       1      6562.00
2026-04-01       1      6618.50
2026-04-02      -1      6622.50

**Merge Datasets**:

In [93]:
# Merge to dataframes of trade history
raw_df_3 = pd.concat([raw_df_1, raw_df_2], axis=0, sort=False)

#Preview
raw_df_3.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 253 entries, 2025-06-22 to 2026-06-15
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Signal       253 non-null    int64
 1   Entry_Price  229 non-null    float64
dtypes: float64(1), int64(1)
memory usage: 5.9 KB

In [94]:
raw_df_3.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 253 entries, 2025-06-22 to 2026-06-15
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Signal       253 non-null    int64
 1   Entry_Price  229 non-null    float64
dtypes: float64(1), int64(1)
memory usage: 5.9 KB