In [32]:
# Import libraries
import pandas as pd 
import numpy as np 
import math 
import statistics 
import matplotlib.pyplot as plt

In [33]:
### Initial parse and inspection ###

# Import and inspect ES_2020-2025.csv 
raw_df = pd.read_csv(r".\Signal_data\ES_2020-2025.csv", sep=";", engine="python") 

# Remove first row of NaN data
raw_df = raw_df.iloc[1:].reset_index(drop=True) 

# Remove the imported but empty last column 
raw_df = raw_df.iloc[:,:-1]

# Display current header 
raw_df.head()

,Quarter,Model_Classification_ID,Entry_Date_ISO,ES_Entry_Price,Direction,Exit_Date_ISO,ES_Exit_Price
0,q3-20,q3-20_1,2020-08-10,"3347,00",-1.0,2020-08-11,"3350,25"
1,q3-20,q3-20_2,2020-08-11,"3350,25",1.0,2020-08-19,"3388,75"
2,q3-20,q3-20_3,2020-08-19,"3388,75",-1.0,2020-08-20,"3370,25"
3,q3-20,q3-20_4,2020-08-20,"3370,25",1.0,2020-08-28,"3488,00"
4,q4-20,q4-20_1,2020-09-25,"3243,50",1.0,2020-09-28,"3291,00"

In [ ]:
### Edit column value types and tidy formatting ###
 
# Change column names
columns = ["Quarter", "Model_Classification_ID", "Entry_Date", "Entry_Price", "Signal", "Exit_Date", "Exit_Price"]
raw_df.columns = columns 

# Change prices to floats 
raw_df["Entry_Price"] = raw_df["Entry_Price"].str.replace(",", ".").astype(float) 
raw_df["Exit_Price"] = raw_df["Exit_Price"].str.replace(",", ".").astype(float)

# Change date strings to datetime 
raw_df["Entry_Date"] = pd.to_datetime(raw_df["Entry_Date"])
raw_df["Exit_Date"] = pd.to_datetime(raw_df["Exit_Date"])

# Review data formatting
raw_df.info()

In [31]:
raw_df.head()

,Quarter,Model_Classification_ID,Entry_Date,Entry_Price,Signal,Exit_Date,Exit_Price
0,q3-20,q3-20_1,2020-08-10,3347.00,-1.0,2020-08-11,3350.25
1,q3-20,q3-20_2,2020-08-11,3350.25,1.0,2020-08-19,3388.75
2,q3-20,q3-20_3,2020-08-19,3388.75,-1.0,2020-08-20,3370.25
3,q3-20,q3-20_4,2020-08-20,3370.25,1.0,2020-08-28,3488.00
4,q4-20,q4-20_1,2020-09-25,3243.50,1.0,2020-09-28,3291.00

**Next Steps**:
- Analyse number of trades, direction of trade and hit rate.
- Analyse typical returns and volatility
- Acquire historical data for each instrument during trade windows to do daily settlement/returns analysis